windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019

task:
    compile_script:
        choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
    binaries_artifacts:
        path: ""