build_task:
    freebsd_instance:
        cpu: 2
        memory: 4G
    install_script:
        pkg update -f
        pkg install -y \
                    git \
                    qt5-qmake \
                    qt5-buildtools \
                    qt5-concurrent \
                    qt5-opengl \
                    qt5-quickcontrols \
                    qt5-quickcontrols2 \
                    qt5-svg \
                    qt5-xml \
                    cmake
    compile_script: