os: windows
language: minimal
    env:
        - PLATFORM: x86
        - QT5_BASE_DIR: C:/Qt/5.12.3/mingw73_32
    cache:
        directories:
            - travis-cache
cache:
    directories:
        - C:/Qt
before_install:
    - echo $TRAVIS_OS_NAME
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then toolchain/travis-cache-windows.sh restore; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then toolchain/travis-install-qt-windows.sh; fi
before_script:
script:
before_cache:
after_script: