language: shell
os: windows
env: PLATFORM=x86 QT5_BASE_DIR=C:/Qt/5.12.3/mingw73_32
cache:
    directories:
        - travis-cache
allow_failures:
    - os: windows
before_install:
    - echo $TRAVIS_OS_NAME
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then toolchain/travis-cache-windows.sh restore; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then toolchain/travis-install-qt-windows.sh; fi
before_script:
    - mkdir build
    - cd build
script:
    - cmake.exe --build . --target Commander_Wars_translations -- -j8
    - cmake.exe --build . --target install -- -j8 --config RELEASE
before_cache:
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then toolchain/travis-cache-windows.sh save; fi
after_script: